spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qmshoes
    username: ASUSVivoBook
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

