package com.lamdangfixbug.qmshoe.user.entity;

public enum Permission {
    CREATE, READ, UPDATE, DELETE, ALL,
    PAYMENT_READ, PAYMENT_UPDATE, PAYMENT_DELETE, PAYMENT_CREATE, PAYMENT_ALL,
    ORDER_READ, ORDER_UPDATE, ORDER_DELETE, ORDER_CREATE, ORDER_ALL,;
}
